export const SKILL_GROUPS = [
  {
    icon: "⚡",
    color: "cyan" as const,
    title: "Languages",
    items: ["C", "C++", "JavaScript", "TypeScript", "SQL"],
  },
  {
    icon: "🖥️",
    color: "emerald" as const,
    title: "Frontend",
    items: [
      "React.js",
      "Next.js",
      "HTML5",
      "CSS3",
      "Tailwind CSS",
      "Bootstrap",
      "MUI",
      "DaisyUI",
      "HeroUI",
    ],
  },
  {
    icon: "🔧",
    color: "purple" as const,
    title: "Backend & Databases",
    items: [
      "Node.js",
      "Express.js",
      "RESTful APIs",
      "PHP (Laravel)",
      "MongoDB",
      "PostgreSQL",
    ],
  },
  {
    icon: "🛠️",
    color: "orange" as const,
    title: "Tools & Concepts",
    items: [
      "Redux",
      "Zustand",
      "TanStack Query",
      "Context API",
      "Git",
      "GitHub",
      "Figma",
      "Vercel",
      "Firebase",
      "OOP",
      "SOLID",
    ],
  },
];
